KEYBOARD_SHARED_EP = yes
DEBUG_ENABLE = yes
CONSOLE_ENABLE = yes

ANALOG_ENABLE = yes
ANALOG_DRIVER_REQUIRED = yes

AUDIO_ENABLE = no
SOLENOID_ENABLE = no
POINTING_DEVICE_ENABLE = no
I2C_DRIVER_REQUIRED = no
